version: "3"

services:
  reverse-proxy:
    container_name: kika-proxy
    image: nginx:stable
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./src/main/nginx/local-proxy.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    container_name: kika-postgres
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kika
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
